### ISSUE TITLE
Could you devolp a hack for Santa's Workshop???

### ISSUE THREAD

**Issue by BackVoid8** [glixzzy/blooket-hack#802] opened 2021-12-17 15:18 UTC

**Comment by gIixzzy** [comment] 2021-12-17 16:11
no

**Comment by marfanis788** [comment] 2021-12-17 16:49
Glixzzy's blunt response be like

**Comment by Greenlio** [comment] 2021-12-17 19:13
Duplicate of #797 but summary:

No, it's limited time, why would we waste time on adding something that'll be gone soon.

**Comment by hecker1234567890** [comment] 2021-12-17 23:21
yee

**Comment by hecker1234567890** [comment] 2021-12-17 23:22
it is common sence

**Comment by glixzzy** [comment] 2021-12-18 23:40
no

**Closed by glixzzy** 2021-12-18 23:40 UTC
Labels: duplicate, the annoying question
