### ISSUE TITLE
More coins

### ISSUE THREAD

**Issue by Jonnnnnnnez** [glixzzy/blooket-hack#1011] opened 2022-01-21 14:28 UTC
Any way to get more than 500 coins?

**Comment by FallGuysFan1234** [comment] 2022-01-21 14:52
Sorry there is no way to get more, its server side which means that there is no way to bypass it at all D:

**Comment by GooseterV** [comment] 2022-01-21 14:57
I believe this is a duplicate of [this](https://github.com/glixzzy/blooket-hack/issues/993)
To answer your question, there is no way to get more than 500 tokens a day.

**Comment by dogs221** [comment] 2022-01-24 19:28
pepe

**Comment by jackisgoated** [comment] 2022-01-27 19:34
pepe popo

**Closed** 2022-02-04 21:32 UTC
Labels: duplicate, wontfix, the annoying question, annoying
